# Generated by Django 5.2.8 on 2026-02-28 23:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_end_order_delivery_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate applied at order time (e.g., 12.00)', max_digits=5),
            preserve_default=False,
        ),
    ]
