# Generated by Django 5.2.8 on 2026-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
