# Generated by Django 5.2.8 on 2026-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
