# Generated by Django 5.2.8 on 2025-12-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
