# Generated by Django 5.2.8 on 2025-12-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_last_verification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_verification_sent',
        ),
    ]
