# Generated by Django 5.2.8 on 2025-12-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_last_verification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_blocked',
        ),
    ]
