# Generated by Django 5.2.8 on 2026-02-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
    ]
