# Generated by Django 5.2.8 on 2026-02-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
