# Generated by Django 5.2.8 on 2026-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='weight_grams',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Snapshot weight per unit in KG', max_digits=6),
            preserve_default=False,
        ),
    ]
