# Generated by Django 5.2.8 on 2026-01-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FLAT', 'Flat')], max_length=10)),
                ('discount_value', models.PositiveIntegerField(help_text='Stored in paise')),
                ('minimum_cart_value', models.PositiveIntegerField(help_text='Stored in paise')),
                ('maximum_discount_amount', models.PositiveIntegerField(blank=True, help_text='Stored in paise', null=True)),
                ('usage_limit_total', models.PositiveIntegerField()),
                ('usage_limit_per_user', models.PositiveIntegerField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
