# Generated by Django 5.2.8 on 2026-02-24 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_end_order_delivery_start_and_more'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='usage_limit_per_user',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='maximum_discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='minimum_cart_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_limit_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usage', to='orders.order')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['promo'], name='promotions__promo_i_462d7a_idx'), models.Index(fields=['promo', 'user'], name='promotions__promo_i_0a1a2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('promo', 'user'), name='unique_user_per_promo')],
            },
        ),
    ]
