# Generated by Django 5.2.8 on 2026-02-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_remove_promocode_usage_limit_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='usage_limit_total',
            field=models.PositiveIntegerField(),
        ),
    ]
