# Generated by Django 5.2.8 on 2026-02-25 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promocode_usage_limit_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Promo code must contain only letters and numbers.', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
