# Generated by Django 5.2.8 on 2025-12-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productvariant_color_alter_productvariant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
