# Generated by Django 5.2.8 on 2026-01-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main product image used in listings & search', null=True, upload_to='products/main/'),
        ),
    ]
