# Generated by Django 5.2.8 on 2026-01-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per KG for this subcategory (surplus pricing)', max_digits=10, null=True),
        ),
    ]
