# Generated by Django 5.2.8 on 2026-01-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_subcategory_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price per KG for this subcategory (surplus pricing)', max_digits=10),
            preserve_default=False,
        ),
    ]
