# Generated by Django 5.2.8 on 2026-01-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_subcategory_price_per_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_per_kg',
        ),
    ]
