# Generated by Django 5.2.8 on 2026-01-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_productvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_color_per_product',
        ),
    ]
