# Generated by Django 5.2.8 on 2026-01-18 17:28

import uuid
from django.db import migrations, models


def populate_product_uuid(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")

    for product in Product.objects.all():
        if not product.uuid:
            product.uuid = uuid.uuid4()
            product.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productvariant_color_and_more'),
    ]

    operations = [
        # 1️⃣ Add UUID field WITHOUT unique constraint
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(
                null=True,
                editable=False,
                db_index=True
            ),
        ),

        # 2️⃣ Populate UUIDs for existing products
        migrations.RunPython(populate_product_uuid),

        # 3️⃣ Enforce uniqueness AFTER data exists
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(
                unique=True,
                editable=False,
                db_index=True
            ),
        ),

        # (unchanged, safe)
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(
                blank=True, null=True, upload_to='products/main/'),
        ),
    ]
