# Generated by Django 5.2.8 on 2026-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('TOP', 'Top sizes (XS, S, M, L, XL, XXL)'), ('WAIST', 'Waist sizes (28, 30, 32, 34, 36)')], default='TOP', help_text='Defines which size system this product uses', max_length=10),
        ),
    ]
