# Generated by Django 5.2.8 on 2026-02-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_size_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['color', 'size_order'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
